### ISSUE TITLE
淘宝无法登录，托块无法过去。

### ISSUE THREAD

**Issue by yoyo-sincerely** [CriseLYJ/awesome-python-login-model#15]
![image](https://user-images.githubusercontent.com/20243998/54072760-635e8580-42ba-11e9-88f7-67da6b812cbb.png)
![image](https://user-images.githubusercontent.com/20243998/54072763-6a859380-42ba-11e9-8d1e-d2cbd6e333c5.png)

**Comment by CriseLYJ** [comment]
你可以尝试使用bilibiili的方式，仅供学习和参考，等我更新也行

**Comment by binbin1139** [comment]
[用代码去拖动了，淘宝一直都是错误，请刷新！           
![image](https://user-images.githubusercontent.com/48936529/55060566-bb63fd00-50ac-11e9-8b4f-ce8359dc9314.png)

-

**Comment by CriseLYJ** [comment]
@yoyo-sincerely 
@binbin1139 
- 淘宝登陆可用了，使用微博的登陆方式

**Comment by AHappySaltedFish** [comment]
哥，用微博登陆也会有验证码吧，不需要吗
