### ISSUE TITLE
请作者解析一下这个事

### ISSUE THREAD

**Issue by YCF** [CriseLYJ/awesome-python-login-model#43]
https://www.v2ex.com/t/550323

**Comment by CriseLYJ** [comment]
嗯  我看过了啊？你们老师写教程不备课吗？？请问为什么备课？？还没到实例就这么杠？

**Comment by CriseLYJ** [comment]
我不会关闭这个，如果有什么问题可以找我，这里也行，邮箱也可以，随时都在，行吧

**Comment by YCF** [comment]
我不是抬杠那个人，我只是过来提醒你一下，别张嘴就喷。

**Comment by CriseLYJ** [comment]
我不喷人https://baike.baidu.com/item/http 你看百度百科行吧。定义的东西，全网不都是一样的吗？？爬虫是什么？到底爬虫是什么，全网不都是一样的吗？我是个弟弟，我不是什么大佬！谢谢

**Comment by abbeyokgo** [comment]
代码全是抄的，你有署过名吗？说什么重构过，难道重构了就能占为己有了？

**Comment by shaun81w** [comment]
Can anyone help me I'm stuck with kodi

**Comment by shaun81w** [comment]
- @shaun81w
