### ISSUE TITLE
豆瓣好像登不上了

### ISSUE THREAD

**Issue by Alalalalaki** [CriseLYJ/awesome-python-login-model#46]
之前行的，昨天想重新存一次cookie发现好像又不行了。看了一圈不知道什么问题。

**Comment by binjingwang** [comment]
data中的数据是什么意思啊？在哪里找的？

**Comment by Alalalalaki** [comment]
自己写了selenium代码解决了, 但还是想知道requests怎么操作...

**Comment by binjingwang** [comment]
兄弟，我还不知道selenium 怎么登陆豆瓣，能否分享学习一下您的代码？

在 2019-04-02 21:23:06，"Alalalalaki" <notifications@github.com> 写道：


自己写了selenium代码解决了, 但还是想知道requests怎么操作...

**Comment by binjingwang** [comment]
兄弟，我还不知道怎么用selenium登陆呢，能否分享学习一下？





在 2019-04-02 21:23:06，"Alalalalaki" <notifications@github.com> 写道：


自己写了selenium代码解决了, 但还是想知道requests怎么操作...

**Comment by CriseLYJ** [comment]
豆瓣登陆已经解决
